const {Schema,model}=require("mongoose")
const menshirtSchema=new Schema({
    _id:{
        type:String,
        required:true
    },
    index:{
        type:Number,
        required:true
    },
    guid:{
        type:String,
        required:true
    },
    isActive:{
        type:Boolean,
        required:true,
    },
    types_of_color:{
        type:[String],
        required:true,
    },
    types_of_sizes:{
        type:[String],
        required:true,
    },
    seller_name:{
        type:String,
        required:true
    },
    review:{
        type:String,
        required:true
    },
    review_id:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    brand_name:{
        type:String,
        required:true
    },
    name_of_fabric:{
        type:String,
        required:true
    },
    img_men:{
        type:String,
        required:true
    },
    amount:{
        type:Number,
        required:true
    }
})
const MenShirts=new model("MenShirts",menshirtSchema)
module.exports=MenShirts