const {Schema,model}=require("mongoose")
const mobileSchema=new Schema({
    brand:{
        type:String,
        require:true
    },
    model:{
        type:String,
        require:true

    },
    release_date:{
        type:String,
        require:true

    },
    specs:{
        display:{
            size:{
                type:String,
                required:true
            },
            resolution:{
                type:String,
                required:true
            }
        },
        processor:{
            type:String,
            required:true
        },
        memory:{
            ram:{
                type:String,
                required:true
            },
            storage:{
                type:String,
                required:true
            }
        },
        camera:{
            rear:{
                type:String,
                required:true
            },
            front:{
                type:String,
                required:true
            }
        },
        battery:{
            capacity:{
                type:String,
                required:true
            },
            type:{
                type:String,
                required:true
            },
        },
        os:{
            type:String,
            required:true
        },
        connectivity:{
            type:[String],
            required:true
        }
    },
    price:{
        type:Number,
        required:true
    },
    availability:{
        online:{
            type:Boolean,
            required:true
        },
        review:{
            type:String,
            required:true
        },
        review_id:{
            type:String,
            required:true
        }
    },
    img_brand:{
        type:String,
        required:true
    },
    img_brand_id:{
        type:String,
        required:true
    },
    amount:{
        type:Number,
        required:true
    }
})

const Mobiles=new model("Mobiles",mobileSchema)
module.exports=Mobiles